name: ik_kg
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: ik-app
        container_name: ik-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: ik_webserver
        restart: unless-stopped
        ports:
            - "9999:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: ik_mysql
        restart: unless-stopped
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ik
            MYSQL_USER: ik_user
            MYSQL_PASSWORD: ik_user_password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/db_data:/var/lib/mysql
#            - mysql_volume:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ik_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "9991:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

#volumes:
#    ./docker/mysql/db_data:
#        driver: local
